"base_path" : "/src/main/resources"
"preserve_hierarchy": true

files: [
 {
  "source" : "/*_i18n.properties",
  "translation" : "/%file_name%_%locale%.%file_extension%",
  "type" : "properties",
  "escape_quotes" : 0,
  "update_option": "update_as_unapproved",
  "new_names": {
   "_i18n": ""
  }
  "languages_mapping": {
   "locale": {
    "es-ES": "es",
    "hy-AM": "hy",
    "pt-PT": "pt",
    "zh-CN": "zh_CN",
    "zh-TW": "zh_TW"
   }
  }
 }
]