"base_path" : "/src/main/resources"
"preserve_hierarchy": true

files: [
 {
  "source" : "/*_i18n.properties",
  "translation" : "/%file_name%_%two_letters_code%.%file_extension%",
  "type" : "properties",
  "escape_quotes" : 0,
  "translation_replace": [
   "_i*n": "",
   "_zh.properties": "_%locale_with_underscore%.properties"
  ]
 }
]