"preserve_hierarchy": true
"export_languages": [ #This disables export of the currently untranslated languages.
  "de",
  "es-ES",
  "fr",
  "pt-PT"
]

"files": [
{
  "source": "/src/main/resources/*.properties",
  "translation": "/src/main/resources/crowdin/%file_name%_%two_letters_code%.%file_extension%",
  "ignore": [
    "/*_??.properties",
    "/log4j.properties",
    "/crowdin"
  ],
  "type": "properties",
  "escape_quotes": 0,
  "update_option": "update_as_unapproved",
  "languages_mapping": {
    "two_letters_code": {
      "zh-CN": "zh_CN",
      "zh-TW": "zh_TW"
    }
  }
}
]
